language: objective-c
osx_image: xcode7
xcode_workspace: TBNetworkingDemo/TBNetworking.xcworkspace
xcode_scheme: TBNetworking
podfile: TBNetworkingDemo/Podfile
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
